name: Javadocs commit

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'microsoft'
    - name: Generate Javadoc
      run: mvn javadoc:javadoc
    - name: Commit Javadocs
      run: |
        git config --global user.email "pedro.games30@gmail.com"
        git config --global user.name "jpedro85"
        git add docs/
        git commit -m "Automatically update docs" || echo "No changes to commit"
        git push
